site_name: Mending Wall
site_description: A Linux app to help GNOME and KDE Plasma desktop environments be more neighborly.
site_url: https://mendingwall.org
repo_url: https://github.com/lawmurray/mendingwall
repo_name: lawmurray/mendingwall
extra:
  social:
    - icon: heart
      link: https://github.com/sponsors/lawmurray
      name: Sponsor
    - icon: material/github
      link: https://github.com/lawmurray
      name: GitHub
    - icon: material/mastodon 
      link: https://fosstodon.org/@lawmurray
      name: Mastodon
    - icon: material/web
      link: https://indii.org
      name: Website (indii.org)
    - icon: material/email
      link: mailto:lawrence@indii.org
      name: Email
extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/favicon.svg
  favicon: assets/favicon.svg
  custom_dir: docs/overrides
  features:
    - navigation.indexes
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: material/github
    admonition:
      success: material/package-down

markdown_extensions:
  - def_list
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - social
  - glightbox
nav:
  - index.md
  - getting-started.md
  - mend-themes.md
  - tidy-menus.md
  - contributing.md
  - questions-and-answers.md
