site_name: Mending Wall
site_description: A Linux app to help GNOME and KDE Plasma desktop environments be more neighborly.
site_url: https://mendingwall.org
repo_url: https://github.com/lawmurray/mendingwall
repo_name: lawmurray/mendingwall
extra:
  social:
    - icon: material/github
      link: https://github.com/lawmurray
    - icon: material/mastodon 
      link: https://fosstodon.org/@lawmurray
    - icon: material/web
      link: https://indii.org
    - icon: material/email
      link: mailto:lawrence@indii.org

theme:
  name: material
  logo: assets/favicon.svg
  favicon: assets/favicon.svg
  features:
    - navigation.indexes
    - navigation.footer
    - announce.dismiss
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: grey
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: grey
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: material/github
    admonition:
      success: material/package-down

markdown_extensions:
  - def_list
  - attr_list
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
      alternate_style: true 
plugins:
  - search
  - social
nav:
  - index.md
  - getting-started.md
  - basic.md
  - Advanced Usage:
    - advanced/index.md
    - advanced/preserve-themes.md
    - advanced/counterpart-applications.md
  - How You Can Help:
    - help/index.md
    - help/preserve-themes.md
    - help/counterpart-applications.md
  - questions-and-answers.md

