version: 2.1

executors:

  linux:
    machine:
      image: ubuntu-2204:current
    resource_class: medium

jobs:

  linux:
    executor: linux
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update --assume-yes
            sudo apt install --assume-yes --no-install-recommends \
              ca-certificates \
              git \
              ssh \
              gcc \
              gettext \
              appstream \
              desktop-file-utils \
              meson \
              python3-gi \
              libgtk-4-dev \
              libglib2.0-bin \
              libglib2.0-dev \
              libadwaita-1-dev
      - run:
          name: Build
          command: |
            meson setup build
            cd build
            meson compile
            meson install
      - run:
          name: Test
          command: |
            mendingwall -h
            mendingwalld -h

  deploy:
    executor: linux
    steps:
      - run:
          name: Trigger package update
          command: |
              curl -X POST https://circleci.com/api/v2/project/gh/lawmurray/download.indii.org/pipeline \
                --header "Circle-Token: $CIRCLE_TOKEN" \
                --header "content-type: application/json" \
                --data '{"branch": "main"}'

workflows:

  version: 2
  all:
    jobs:
      - linux
      - deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
