version: 2.1

executors:

  linux:
    docker:
      - image: ubuntu:latest
    resource_class: small
    environment:
      DEBIAN_FRONTEND: noninteractive

jobs:

  linux:
    executor: linux
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt update --assume-yes
            apt install --assume-yes --no-install-recommends \
              ca-certificates \
              git \
              ssh \
              gcc \
              gettext \
              appstream \
              desktop-file-utils \
              meson \
              libgtk-4-dev \
              libglib2.0-bin \
              libglib2.0-dev \
              libadwaita-1-dev
      - run:
          name: Build
          command: |
            meson setup build
            cd build
            meson compile
            meson install
      - run:
          name: Test
          command: |
            mendingwall -h
            mendingwalld -h

workflows:

  version: 2
  all:
    jobs:
      - linux
