version: 2.1

executors:

  linux:
    docker:
      - image: ubuntu:latest
    resource_class: small
    environment:
      DEBIAN_FRONTEND: noninteractive

commands:

  environment:
    steps:
      - run:
          name: Install dependencies
          command: |
            apt update --assume-yes
            apt install --assume-yes --nto-install-recommends \
              ca-certificates \
              curl \
              git \
              ssh \
              gcc \
              gettext \
              appstream \
              desktop-file-utils \
              meson \
              python3-gi \
              libgtk-4-dev \
              libglib2.0-bin \
              libglib2.0-dev \
              libadwaita-1-dev

  build:
    steps:
      - run:
          name: Build
          command: |
            meson setup build
            cd build
            meson compile
            meson install

  test:
    steps:
      - run:
          name: "Test: Smoke"
          command: |
            mendingwall -h
            mendingwalld -h
      - run:
          name: "Test: Enable"
          command: |
            `gsettings get org.indii.mendingwall themes` == false || exit 1
            `gsettings get org.indii.mendingwall menu` == false || exit 1
            gsettings set org.indii.mendingwall themes true
            gsettings set org.indii.mendingwall menus true
            `gsettings get org.indii.mendingwall themes` == true || exit 1
            `gsettings get org.indii.mendingwall menu` == true || exit 1

jobs:

  linux:
    executor: linux
    steps:
      - checkout
      - environment
      - build
      - test

  deploy:
    executor: linux
    steps:
      - environment
      - run:
          name: Trigger package update
          command: |
              curl -X POST https://circleci.com/api/v2/project/gh/lawmurray/download.indii.org/pipeline \
                --header "Circle-Token: $CIRCLE_TOKEN" \
                --header "content-type: application/json" \
                --data '{"branch": "main"}'

workflows:

  version: 2
  all:
    jobs:
      - linux
      - deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
