name: mendingwall
title: Mending Wall
version: git
adopt-info: mendingwall

base: core24
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  mendingwall:
    plugin: meson
    source: https://github.com/lawmurray/mendingwall.git
    parse-info:
      - usr/local/share/metainfo/org.indii.mendingwall.metainfo.xml
    build-packages:
      - meson
      - blueprint-compiler
      - gettext
      - appstream
      - desktop-file-utils
      - libgtk-4-dev
      - libglib2.0-dev
      - libadwaita-1-dev
      - libportal-dev
      - libportal-gtk4-dev
      - libportal-gtk3-dev
    stage-packages:
      - libgtk-4-1
      - libadwaita-1-0
      - libportal1

apps:
  mendingwall:
    command: usr/local/bin/mendingwall
  mendingwalld:
    command: usr/local/bin/mendingwalld

