name: mendingwall
title: Mending Wall
version: git
adopt-info: mendingwall

base: core24
grade: stable
confinement: strict

parts:
  mendingwall:
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Dc_args=-DENABLE_SPAWN
    source: .
    parse-info:
      - usr/share/metainfo/org.indii.mendingwall.metainfo.xml
    build-packages:
      - git
      - meson
      - gettext
      - appstream
      - desktop-file-utils
      - libgtk-4-dev
      - libglib2.0-dev
      - libglib2.0-bin
      - libadwaita-1-dev
      - libportal-dev
      - libportal-gtk4-dev
      - libportal-gtk3-dev
    stage-packages:
      - libgtk-4-1
      - libadwaita-1-0
      - libportal1

slots:
  mendingwall:
    interface: dbus
    bus: session
    name: org.indii.mendingwall

  mendingwalld:
    interface: dbus
    bus: session
    name: org.indii.mendingwall.watch

apps:
  mendingwall:
    command: usr/bin/mendingwall
    desktop: usr/share/applications/org.indii.mendingwall.desktop
    common-id: org.indii.mendingwall
    extensions:
      - gnome
    slots:
      - mendingwall

  mendingwalld:
    command: usr/bin/mendingwalld
    common-id: org.indii.mendingwall.watch
    extensions:
      - gnome
    slots:
      - mendingwalld
