name: mendingwall
title: Mending Wall
version: git
adopt-info: mendingwall

base: core24
grade: stable
confinement: strict

parts:
  mendingwall:
    plugin: meson
    meson-parameters:
      - "--buildtype=release"
      - "--prefix=/usr"
      - "-Dc_args=-DBUILD_FOR_SNAP"
    source: .
    parse-info:
      - usr/share/metainfo/org.indii.mendingwall.metainfo.xml
    build-packages:
      - git

slots:
  dbus-mendingwall:
    interface: dbus
    bus: session
    name: org.indii.mendingwall

  dbus-mendingwallcli:
    interface: dbus
    bus: session
    name: org.indii.mendingwall.cli

  dbus-mendingwalld:
    interface: dbus
    bus: session
    name: org.indii.mendingwall.watch

plugs:
  dconf-dbus:
    interface: dbus
    bus: session
    name: ca.desrt.dconf

  dconf-db:
    interface: personal-files
    write:
      - $HOME/.config/dconf/user

  user-config:
    interface: personal-files
    write:
      # access to user configuration files of desktop environments that are
      # saved and restored, as well as installation of autostart files
      - $HOME/.config

  user-share:
    interface: personal-files
    write:
      # access to user application directory to which to write updated
      # .desktop files
      - $HOME/.local/share/applications

  system-share:
    interface: system-files
    read:
      # access to system application directories from which to read .desktop
      # files of installed applications
      - /var/lib/snapd/hostfs/var/lib/flatpak/exports/share/applications
      - /var/lib/snapd/hostfs/var/lib/snapd/desktop/applications
      - /var/lib/snapd/hostfs/usr/local/share/applications
      - /var/lib/snapd/hostfs/usr/share/applications

# plugs are the same for all apps, as mendingwall and mendingwallcli may
# launch mendingwalld, and if so it will inherit their configuration
apps:
  mendingwall:
    command: usr/bin/mendingwall
    desktop: usr/share/applications/org.indii.mendingwall.desktop
    common-id: org.indii.mendingwall
    extensions:
      - gnome
    slots:
      - dbus-mendingwall
      - dbus-mendingwalld
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - dconf-dbus
      - dconf-db
      - user-config
      - user-share
      - system-share

  mendingwallcli:
    command: usr/bin/mendingwallcli
    common-id: org.indii.mendingwall.cli
    extensions:
      - gnome
    slots:
      - dbus-mendingwallcli
      - dbus-mendingwalld
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - dconf-dbus
      - dconf-db
      - user-config
      - user-share
      - system-share

  mendingwalld:
    command: usr/bin/mendingwalld
    common-id: org.indii.mendingwall.watch
    extensions:
      - gnome
    slots:
      - dbus-mendingwalld
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - dconf-dbus
      - dconf-db
      - user-config
      - user-share
      - system-share
