name: mendingwall
title: Mending Wall
version: git
adopt-info: mendingwall

base: core24
grade: stable
confinement: strict

parts:
  mendingwall:
    plugin: meson
    meson-parameters:
      - "--buildtype=release"
      - "--prefix=/usr"
      - "-Dbuildfor=snap"
    source: .
    parse-info:
      - usr/share/metainfo/org.indii.mendingwall.metainfo.xml
    build-packages:
      - git
      - blueprint-compiler

slots:
  dbus-mendingwall:
    interface: dbus
    bus: session
    name: org.indii.mendingwall

  dbus-mendingwallcli:
    interface: dbus
    bus: session
    name: org.indii.mendingwall.cli

  dbus-mendingwalld:
    interface: dbus
    bus: session
    name: org.indii.mendingwall.watch

plugs:

  user-config:
    interface: personal-files
    write:
      # access to user configuration files of desktop environments that are
      # saved and restored, as well as installation of autostart files
      - $HOME/.config

  user-share:
    interface: personal-files
    write:
      # access to user application directory to which to write updated
      # .desktop files
      - $HOME/.local/share/applications

  system-share:
    interface: system-files
    read:
      # access to system application directories from which to read .desktop
      # files of installed applications; for the first, we want access to
      # /var/lib/snapd/hostfs/var/lib/flatpak/exports/share/applications, but
      # this is a directory of symlinks to other directories under
      # /var/lib/snapd/hostfs/var/lib/flatpak, so we request access to that
      - /var/lib/snapd/hostfs/var/lib/flatpak
      - /var/lib/snapd/hostfs/usr/local/share/applications
      - /var/lib/snapd/hostfs/usr/share/applications
      - /var/lib/snapd/hostfs/var/lib/snapd/desktop/applications

# plugs are the same for all apps, as mendingwall and mendingwallcli may
# launch mendingwalld, and if so it will inherit their configuration
apps:
  mendingwall:
    command: usr/bin/mendingwall
    desktop: usr/share/applications/org.indii.mendingwall.desktop
    common-id: org.indii.mendingwall
    bus-name: org.indii.mendingwall
    extensions:
      - gnome
    slots:
      - dbus-mendingwall
      - dbus-mendingwallcli
      - dbus-mendingwalld
    plugs:
      - desktop
      - desktop-legacy
      - opengl
      - wayland
      - x11
      - gsettings
      - user-config
      - user-share
      - system-share

  mendingwallcli:
    command: usr/bin/mendingwallcli
    common-id: org.indii.mendingwall
    bus-name: org.indii.mendingwall.cli
    extensions:
      - gnome
    slots:
      - dbus-mendingwall
      - dbus-mendingwallcli
      - dbus-mendingwalld
    plugs:
      - gsettings
      - user-config
      - user-share
      - system-share

  mendingwalld:
    command: usr/bin/mendingwalld
    common-id: org.indii.mendingwall
    bus-name: org.indii.mendingwall.watch
    extensions:
      - gnome
    slots:
      - dbus-mendingwall
      - dbus-mendingwallcli
      - dbus-mendingwalld
    plugs:
      - gsettings
      - user-config
      - user-share
      - system-share
